package com.upb.Model;
// Generated 2 f�vr. 2023, 12:43:05 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commune generated by hbm2java
 */
@Entity
@Table(name = "commune", catalog = "locationresidence")
public class Commune implements java.io.Serializable {

	private Integer idCommune;
	private String nomCommune;

	public Commune() {
	}

	public Commune(String nomCommune) {
		this.nomCommune = nomCommune;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_COMMUNE", unique = true, nullable = false)
	public Integer getIdCommune() {
		return this.idCommune;
	}

	public void setIdCommune(Integer idCommune) {
		this.idCommune = idCommune;
	}

	@Column(name = "NOM_COMMUNE", length = 50)
	public String getNomCommune() {
		return this.nomCommune;
	}

	public void setNomCommune(String nomCommune) {
		this.nomCommune = nomCommune;
	}

}
