package com.upb.Model;
// Generated 2 f�vr. 2023, 12:43:05 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name = "contrat", catalog = "locationresidence")
public class Contrat implements java.io.Serializable {

	private Integer idContrat;
	private int idLocataire;

	public Contrat() {
	}

	public Contrat(int idLocataire) {
		this.idLocataire = idLocataire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_CONTRAT", unique = true, nullable = false)
	public Integer getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(Integer idContrat) {
		this.idContrat = idContrat;
	}

	@Column(name = "ID_LOCATAIRE", nullable = false)
	public int getIdLocataire() {
		return this.idLocataire;
	}

	public void setIdLocataire(int idLocataire) {
		this.idLocataire = idLocataire;
	}

}
