package com.upb.Model;
// Generated 2 f�vr. 2023, 12:43:05 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "locationresidence")
public class Facture implements java.io.Serializable {

	private Integer numFacture;
	private int idLogement;
	private Date dateFacture;
	private Integer prixFacture;

	public Facture() {
	}

	public Facture(int idLogement) {
		this.idLogement = idLogement;
	}

	public Facture(int idLogement, Date dateFacture, Integer prixFacture) {
		this.idLogement = idLogement;
		this.dateFacture = dateFacture;
		this.prixFacture = prixFacture;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NUM_FACTURE", unique = true, nullable = false)
	public Integer getNumFacture() {
		return this.numFacture;
	}

	public void setNumFacture(Integer numFacture) {
		this.numFacture = numFacture;
	}

	@Column(name = "ID_LOGEMENT", nullable = false)
	public int getIdLogement() {
		return this.idLogement;
	}

	public void setIdLogement(int idLogement) {
		this.idLogement = idLogement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FACTURE", length = 10)
	public Date getDateFacture() {
		return this.dateFacture;
	}

	public void setDateFacture(Date dateFacture) {
		this.dateFacture = dateFacture;
	}

	@Column(name = "PRIX_FACTURE")
	public Integer getPrixFacture() {
		return this.prixFacture;
	}

	public void setPrixFacture(Integer prixFacture) {
		this.prixFacture = prixFacture;
	}

}
