package com.upb.Model;
// Generated 2 f�vr. 2023, 12:43:05 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "locationresidence")
public class Location implements java.io.Serializable {

	private int idLocation;
	private int idLocataire;
	private int idLogement;
	private Date dateDebut;
	private Date dateFin;

	public Location() {
	}

	public Location(int idLocation, int idLocataire, int idLogement) {
		this.idLocation = idLocation;
		this.idLocataire = idLocataire;
		this.idLogement = idLogement;
	}

	public Location(int idLocation, int idLocataire, int idLogement, Date dateDebut, Date dateFin) {
		this.idLocation = idLocation;
		this.idLocataire = idLocataire;
		this.idLogement = idLogement;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	@Id

	@Column(name = "id_Location", unique = true, nullable = false)
	public int getIdLocation() {
		return this.idLocation;
	}

	public void setIdLocation(int idLocation) {
		this.idLocation = idLocation;
	}

	@Column(name = "ID_LOCATAIRE", nullable = false)
	public int getIdLocataire() {
		return this.idLocataire;
	}

	public void setIdLocataire(int idLocataire) {
		this.idLocataire = idLocataire;
	}

	@Column(name = "ID_LOGEMENT", nullable = false)
	public int getIdLogement() {
		return this.idLogement;
	}

	public void setIdLogement(int idLogement) {
		this.idLogement = idLogement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT", length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
