package com.upb.Model;
// Generated 2 f�vr. 2023, 12:43:05 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Locataire generated by hbm2java
 */
@Entity
@Table(name = "locataire", catalog = "locationresidence")
public class Locataire implements java.io.Serializable {

	private Integer idLocataire;
	private int idAdmin;
	private String nomLocataire;
	private Date dateNaissance;
	private Integer cin;
	private Integer telel;

	public Locataire() {
	}

	public Locataire(int idAdmin) {
		this.idAdmin = idAdmin;
	}

	public Locataire(int idAdmin, String nomLocataire, Date dateNaissance, Integer cin, Integer telel) {
		this.idAdmin = idAdmin;
		this.nomLocataire = nomLocataire;
		this.dateNaissance = dateNaissance;
		this.cin = cin;
		this.telel = telel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_LOCATAIRE", unique = true, nullable = false)
	public Integer getIdLocataire() {
		return this.idLocataire;
	}

	public void setIdLocataire(Integer idLocataire) {
		this.idLocataire = idLocataire;
	}

	@Column(name = "ID_ADMIN", nullable = false)
	public int getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(int idAdmin) {
		this.idAdmin = idAdmin;
	}

	@Column(name = "NOM_LOCATAIRE", length = 30)
	public String getNomLocataire() {
		return this.nomLocataire;
	}

	public void setNomLocataire(String nomLocataire) {
		this.nomLocataire = nomLocataire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAISSANCE", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "CIN")
	public Integer getCin() {
		return this.cin;
	}

	public void setCin(Integer cin) {
		this.cin = cin;
	}

	@Column(name = "TELEL")
	public Integer getTelel() {
		return this.telel;
	}

	public void setTelel(Integer telel) {
		this.telel = telel;
	}

}
