package com.upb.Model;
// Generated 2 f�vr. 2023, 12:43:05 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Logement generated by hbm2java
 */
@Entity
@Table(name = "logement", catalog = "locationresidence")
public class Logement implements java.io.Serializable {

	private Integer idLogement;
	private int idAdmin;
	private int idType;
	private int idCommune;
	private String adresse;
	private Integer superficie;
	private Integer prix;
	private String type;
	private String region;

	public Logement() {
	}

	public Logement(int idAdmin, int idType, int idCommune) {
		this.idAdmin = idAdmin;
		this.idType = idType;
		this.idCommune = idCommune;
	}

	public Logement(int idAdmin, int idType, int idCommune, String adresse, Integer superficie, Integer prix,
			String type, String region) {
		this.idAdmin = idAdmin;
		this.idType = idType;
		this.idCommune = idCommune;
		this.adresse = adresse;
		this.superficie = superficie;
		this.prix = prix;
		this.type = type;
		this.region = region;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_LOGEMENT", unique = true, nullable = false)
	public Integer getIdLogement() {
		return this.idLogement;
	}

	public void setIdLogement(Integer idLogement) {
		this.idLogement = idLogement;
	}

	@Column(name = "ID_ADMIN", nullable = false)
	public int getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(int idAdmin) {
		this.idAdmin = idAdmin;
	}

	@Column(name = "ID_TYPE", nullable = false)
	public int getIdType() {
		return this.idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	@Column(name = "ID_COMMUNE", nullable = false)
	public int getIdCommune() {
		return this.idCommune;
	}

	public void setIdCommune(int idCommune) {
		this.idCommune = idCommune;
	}

	@Column(name = "ADRESSE", length = 50)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "SUPERFICIE")
	public Integer getSuperficie() {
		return this.superficie;
	}

	public void setSuperficie(Integer superficie) {
		this.superficie = superficie;
	}

	@Column(name = "PRIX")
	public Integer getPrix() {
		return this.prix;
	}

	public void setPrix(Integer prix) {
		this.prix = prix;
	}

	@Column(name = "TYPE", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "REGION", length = 50)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

}
