package com.upb.Model;
// Generated 2 f�vr. 2023, 12:43:05 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TypeLogement generated by hbm2java
 */
@Entity
@Table(name = "type_logement", catalog = "locationresidence")
public class TypeLogement implements java.io.Serializable {

	private Integer idType;
	private String nomType;
	private Integer formulaire;

	public TypeLogement() {
	}

	public TypeLogement(String nomType, Integer formulaire) {
		this.nomType = nomType;
		this.formulaire = formulaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TYPE", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "NOM_TYPE", length = 50)
	public String getNomType() {
		return this.nomType;
	}

	public void setNomType(String nomType) {
		this.nomType = nomType;
	}

	@Column(name = "FORMULAIRE")
	public Integer getFormulaire() {
		return this.formulaire;
	}

	public void setFormulaire(Integer formulaire) {
		this.formulaire = formulaire;
	}

}
